CREATE SEQUENCE USER_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE COURSE_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE STUDENT_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE STUDENT_COURSE_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE COURSE_COORDINATOR_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE RECEIVING_INSTITUTION_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE SENDING_INSTITUTION_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE STUDENT_SENDING_INSTITUTION_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE COURSE_OWNED_COORDINATOR_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE SEQUENCE SENDING_INSTITUTION_COORDINATOR_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO CYCLE;

CREATE TABLE USERS
(
    ID       bigint DEFAULT NEXTVAL('USER_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE COURSES
(
    ID       bigint DEFAULT NEXTVAL('COURSE_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE STUDENTS
(
    ID       bigint DEFAULT NEXTVAL('STUDENT_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE STUDENT_COURSES
(
    ID       bigint DEFAULT NEXTVAL('STUDENT_COURSE_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE COURSE_COORDINATORS
(
    ID       bigint DEFAULT NEXTVAL('COURSE_COORDINATOR_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE RECEIVING_INSTITUTIONS
(
    ID       bigint DEFAULT NEXTVAL('RECEIVING_INSTITUTION_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE SENDING_INSTITUTIONS
(
    ID       bigint DEFAULT NEXTVAL('SENDING_INSTITUTION_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE STUDENT_SENDING_INSTITUTIONS
(
    ID       bigint DEFAULT NEXTVAL('STUDENT_SENDING_INSTITUTION_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE COURSE_OWNED_COORDINATORS
(
    ID       bigint DEFAULT NEXTVAL('COURSE_OWNED_COORDINATOR_SEQUENCE') PRIMARY KEY,
);

CREATE TABLE SENDING_INSTITUTION_COORDINATORS
(
    ID       bigint DEFAULT NEXTVAL('SENDING_INSTITUTION_COORDINATOR_SEQUENCE') PRIMARY KEY,
);
